name: sophiread
channels:
  - conda-forge
dependencies:
  - cmake
  - clang-format
  - cxx-compiler
  - hdf5
  - gmock
  - qt
  - gtest
  - qwt
  - eigen
  - mlpack
  - cereal
  - tbb-devel
  - spdlog

  # documentation
  - doxygen
  - graphviz
